routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/sendCorn', 'BackupMySqlController@sendCorn');
Route::post('/login', 'Auth\LoginController@login');
Auth::routes();

//Admin Route
Route::group(['prefix' => 'mediuswareadmin', 'middleware' => 'auth'], function () {
    Route::get('dashboard', 'Admin\DashboardController@index')->name('home');
    //services
    Route::resource('services', 'Admin\ServicesController');
    Route::post('service/sortable', 'Admin\ServicesController@sortable');
    //category
    Route::resource('category', 'Admin\CategoryController');
    //portfolio
    Route::resource('portfolio', 'Admin\PortfolioController');
    Route::post('portfolio/sortable', 'Admin\PortfolioController@sortable');
    Route::get('portfolio/image/{id}/delete', 'Admin\PortfolioController@portfolioImageDelete');
    //team
    Route::resource('team', 'Admin\TeamController');
    Route::post('team/sortable', 'Admin\TeamController@sortable');
    //slider
    Route::resource('slider', 'Admin\SliderController');
    Route::post('slider/sortable', 'Admin\SliderController@sortable');
    //feature
    Route::resource('feature', 'Admin\FeatureController');
    //setting
    Route::get('setting', 'Admin\DashboardController@setting');
    Route::post('setting/store', 'Admin\DashboardController@settingStore');
    //career
    Route::resource('careers', 'Admin\CareerController');
    //contact
    Route::get('contacts', 'Admin\DashboardController@contacts');
    Route::get('contact/delete/{id}', 'Admin\DashboardController@contactDelete');
    //about
    Route::resource('about', 'Admin\AboutController');
    Route::post('about/sortable', 'Admin\AboutController@sortable');
    //technology
    Route::resource('technology', 'Admin\TechnologyController');
    Route::post('technology/sortable', 'Admin\TechnologyController@sortable');
    //client
    Route::resource('client', 'Admin\ClientController');
    Route::post('client/sortable', 'Admin\ClientController@sortable');
    //client
    Route::resource('partner', 'Admin\PartnerController');
    Route::post('partner/sortable', 'Admin\PartnerController@sortable');
    //informative
    Route::resource('informative-text', 'Admin\InformativeTextController');
    //informative
    Route::resource('testimonial', 'Admin\TestimonialController');
    Route::get('profile', 'Admin\ProfileController@index')->name('profile.index');
    Route::post('profile-update', 'Admin\ProfileController@updateProfile')->name('profile.update');
    Route::post('updatepassword', 'Admin\ProfileController@updatePassword')->name('updatePassword');

    Route::group(['middleware' => 'admin'], function () {
        //user
        Route::resource('user', 'Admin\UserController');
        Route::post('user/sortable', 'Admin\UserController@sortable');
        Route::resource('db-backup', 'Admin\BackupController');
    });

});

//Frontend Route
Route::get('/get-abouts', 'WebsiteController@getAbouts');
Route::get('/get-portfolios-showcase', 'WebsiteController@getPortfolioShowcase');
Route::get('/get-portfolios', 'WebsiteController@getPortfolios');
Route::get('/get-portfolios/{slug}', 'WebsiteController@getPortfolios');
Route::get('/get-portfolio-details/{slug}', 'WebsiteController@getPortfolioDetails');
Route::get('/get-categories', 'WebsiteController@getCategories');
Route::get('/get-features', 'WebsiteController@getFeatures');
Route::get('/get-feature-details/{slug}', 'WebsiteController@getFeatureDetails');
Route::get('/get-services', 'WebsiteController@getServices');
Route::get('/get-service-details/{slug}', 'WebsiteController@getServiceDetails');
Route::get('/get-setting', 'WebsiteController@getSettingInfo');
Route::get('/get-teams', 'WebsiteController@getTeam');
Route::get('/get-team-details/{slug}', 'WebsiteController@getTeamDetails');
Route::post('/contact-store', 'WebsiteController@contactStore');
Route::post('/team-contact-store', 'WebsiteController@teamContactStore');
Route::post('/newsletter-store', 'WebsiteController@newsletterStore');
Route::get('/get-technology', 'WebsiteController@getTechnology');
Route::get('/get-clients', 'WebsiteController@getClients');
Route::get('/get-sliders', 'WebsiteController@getSliders');
Route::get('/get-informative-text', 'WebsiteController@getInformativeText');
Route::get('/get-testimonials', 'WebsiteController@getTestimonials');
Route::get('/get-partners', 'WebsiteController@getPartners');
Route::get('/get-careers', 'WebsiteController@getCareers');
Route::get('/get-career-details/{slug}', 'WebsiteController@getCareerDetails');


Route::get('/{vue_route?}', 'WebsiteController@home')->where('vue_route', '(.*)');

app/Models/DbBackup.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class DbBackup extends Model
{
    protected $guarded = ['id'];
}

resources/views/admin/db-backup/index.blade.php
@extends('admin.master')

@section('title')
    Mediusware | DB Backup
@endsection

@section('content')
    <!-- Bread crumb and right sidebar toggle -->
    <div class="page-breadcrumb border-bottom">
        <div class="row">
            <div class="col-lg-3 col-md-4 col-xs-12 align-self-center">
                <h5 class="font-medium text-uppercase mb-0">DB Backup</h5>
            </div>
            <div class="col-lg-9 col-md-8 col-xs-12 align-self-center">

                <nav aria-label="breadcrumb" class="mt-2 float-md-right float-left">
                    <ol class="breadcrumb mb-0 justify-content-end p-0">
                        <li class="breadcrumb-item"><a href="{!! url('/home') !!}">Home</a></li>
                        <li class="breadcrumb-item"><a href="{!! route('home') !!}">Dashboard</a></li>
                        <li class="breadcrumb-item active" aria-current="page">DB Backup</li>
                    </ol>
                </nav>
            </div>
        </div>
    </div>
    
    <!-- End Bread crumb and right sidebar toggle -->
    
    
    <!-- Container fluid  -->

    <div class="page-content container-fluid">

    @include('admin.include.alert')
        <!-- First Cards Row  -->
        <div class="row">
            <div class="col-12">
                <div class="material-card card">
                    <div class="card-body">
                        <div class="row">
                            <div class="col-md-10">
                                <h4 class="card-title">DB Backup</h4>
                            </div>
                            <div class="col-12">
                                <hr>
                            </div>
                        </div>

                        <div class="table-responsive">
                            <table id="row_create_call" class="table table-striped table-hover table-bordered display" style="width:100%">
                                <thead>
                                <tr>
                                    <th width="5%">#</th>
                                    <th>File</th>
                                    <th>Date</th>
                                    <th width="10%">Action</th>
                                </tr>
                                </thead>
                                <tbody id="tablecontents">
                                    @foreach($records as $key => $val)
                                    <tr class="row1" data-id="{{ $val->id }}">
                                        <td>{!! ++$key !!}</td>
                                        <td><a href="{{ route('db-backup.show', $val->id)}}">{{ $val->export_file }}</a></td>
                                        <td>{!! $val->created_at !!}</td>
                                        <td>
                                            <form action="{{ route('db-backup.destroy', $val->id)}}" method="post">
                                                @csrf
                                                @method('DELETE')
                                                <a href="{{ route('db-backup.show', $val->id)}}" class="btn btn-info btn-circle"><i class="fa fa-download"></i> </a>
                                                <button type="submit" onclick="return confirm('Are you sure...?')" class="btn btn-danger btn-circle"><i class="fa fa-trash"></i> </button>
                                            </form>
                                        </td>
                                    </tr>
                                    @endforeach
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
        </div>

    </div>


@endsection

@section('page_js')
    <script type="text/javascript">
        $(function () {
            $( "#tablecontents" ).sortable({
                items: "tr",
                cursor: 'move',
                opacity: 0.6,
                update: function() {
                    sendOrderToServer();
                }
            });

            function sendOrderToServer() {
                var order = [];

                $('tr.row1').each(function(index,element) {
                    order.push({
                        id: $(this).attr('data-id'),
                        position: index+1,
                    });
                });

                $.ajax({
                    type: "POST",
                    dataType: "json",
                    url: "{{ url('projectman/project/sortable') }}",
                    data: {
                        order:order,
                        _token: '{{csrf_token()}}'
                    },
                    success: function(response) {
                        if (response.status == "success") {
                            console.log(response);
                        } else {
                            console.log(response);
                        }
                    }
                });

            }
        });

    </script>
@endsection